# Generated by Django 2.2.6 on 2019-10-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default='Click for more details', max_length=300),
        ),
    ]
