# Generated by Django 2.2.6 on 2019-10-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default='Click at the title for more details.', max_length=300),
        ),
    ]
