# Generated by Django 2.2.6 on 2019-10-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191007_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='Click at the title for more details.', max_length=300),
        ),
    ]
